Fix nogui VERSION bug. (#13)
## Motivation

You will be unable to install ROCm if you build the runfile installer with the `nogui` flag. You will instead get the following error:

```shell
Error: ROCm version information not available. setup_rocm_version_info() should be called first.
```

## Technical Details

The build script is implicitly relying on CMakeLists.txt to copy the VERSION file that `write_version` creates in `runfile-installer/build-installer/build-installer.sh`. If user builds the runfile installer with the `nogui` flag, then this VERSION file doesn't get copied. Instead, it ends up using the default VERSION file in the repo `runfile-installer/rocm-installer/VERSION` which doesn't contain the ROCm version, causing the install to fail.

## Test Plan

Build and install ROCm with and without `nogui` flag

```shell
# Build with nogui flag
bash build-runfile-installer.sh config=config/nightly.config pulltag=20260427 pullrunid=24974858739 pullrocmver=7.13.0 pullpkg=amdrocm-core-sdk rocm-archs=gfx110x pullamdgpu=release,30.30.1 buildname=test mscomp=hybriddev nogui

# Install
bash rocm-installer-7.13.0-test-53.run deps=install rocm gfx=gfx110x compo=core-sdk
```

```shell
# Build with nogui flag
bash build-runfile-installer.sh config=config/nightly.config pulltag=20260427 pullrunid=24974858739 pullrocmver=7.13.0 pullpkg=amdrocm-core-sdk rocm-archs=gfx110x pullamdgpu=release,30.30.1 buildname=test-without-nogui mscomp=hybriddev

# Install
bash rocm-installer-7.13.0-test-without-nogui-53.run deps=install rocm gfx=gfx110x compo=core-sdk
```
## Test Result

Able to install ROCm on a baremetal Navi31XTX on RHEL 9.6 without any issues.